name: Release Obsidian plugin

on:
  push:
    branches:
      - test-release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Verify build output
        run: |
          ls -la
          if [ ! -f "main.js" ]; then echo "Error: main.js not found!"; exit 1; fi
          if [ ! -f "styles.css" ]; then echo "Error: styles.css not found!"; exit 1; fi
          if [ ! -f "manifest.json" ]; then echo "Error: manifest.json not found!"; exit 1; fi

      - name: Temporarily stage built files for release
        run: git add -f main.js styles.css manifest.json

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="test-$(date +%Y%m%d-%H%M%S)"

          gh release create "$tag" \
            --title="Test Release: $tag" \
            --draft \
            main.js manifest.json styles.css
